import { Rubik } from "next/font/google";
import "./globals.css";

// Componants
import Navbar from "./components/Navbar";

const rubik = Rubik({ subsets: ["latin"] });  // Loading the font which we first imported

export const metadata = {
  title: "Auto Feeder Project",
  description: "Generated by Default",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=
        {rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
