
import { Rubik } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/SessionProvider";
import { getSession } from "./actions/getCurrentUser";


// Componants
import Navbar from "./components/Navbar";

const rubik = Rubik({ subsets: ["latin"] });  // Loading the font which we first imported

export const metadata = {
  title: "Auto Feeder Project",
  description: "Generated by Default",
};

export default async function RootLayout({ children }) {

  const session = await getSession();
  
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Providers>
          {session && <Navbar />}
          {children}
        </Providers>
      </body>
    </html>
  );


}
